### ISSUE TITLE
bridge function on KVM broken

### ISSUE THREAD

**Issue by phillxnet** [openSUSE/suse-module-tools#11]
On Leap15.1 in the past 3 days an update broke my KVM bridge arrangement.
I have tracked this down to:
```
Repository     : Main Update Repository                                                
Name           : suse-module-tools                                                     
Version        : 15.1.18-lp151.2.4.1                                                   
Arch           : x86_64                                                                
Vendor         : openSUSE           
```
Via rollback to snapshot I returned my system to a working state and individually applied each update in turn. This version ended up breaking networking for all my VM's on that Leap15.1 system.

Reverting to the snapshot just prior to this update restored KVM network funciton:

Working version of suse-module-tools:
```
Status         : out-of-date (version 15.1.13-lp151.1.1 installed) 
```

I tried to find the OBS entry for this package but received 503 maintenance:
https://software.opensuse.org/package/suse-module-tools

Bridge network setup used for KVM is configured via Network Manager:
```
nmcli con show
NAME               UUID                                  TYPE      DEVICE 
bridge-br0         ac4cc651-5bcd-4bcd-b302-4f3cb370393b  bridge    br0    
bridge-slave-p4p2  1da5ea09-ab13-4cf6-9d23-a57ebbee7abf  ethernet  p4p2   
vnet0              b54bbb49-52dc-4ef2-ac10-6abefeaa91b7  tun       vnet0  
vnet1              dd887ab9-5437-4fc0-bd06-aa0b200b0af3  tun       vnet1  
vnet2              5f6e43b2-f948-4be9-b084-99a60940ef63  tun       vnet2  
```
with br0 setup via command line:
```
build:~ # nmcli dev show br0
GENERAL.DEVICE:                         br0
GENERAL.TYPE:                           bridge
GENERAL.HWADDR:                         A4:1F:72:##:##:##
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     bridge-br0
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/1
IP4.ADDRESS[1]:                         192.168.1.117/24
IP4.GATEWAY:                            192.168.1.1
IP4.ROUTE[1]:                           dst = 0.0.0.0/0, nh = 192.168.1.1, mt = 425
IP4.ROUTE[2]:                           dst = 192.168.1.0/24, nh = 0.0.0.0, mt = 425
IP4.DNS[1]:                             192.168.1.1
IP4.DOMAIN[1]:                          lan
IP6.ADDRESS[1]:                         fe80::7ed1:ec96:f7d7:8176/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = ff00::/8, nh = ::, mt = 256, table=255
IP6.ROUTE[2]:                           dst = fe80::/64, nh = ::, mt = 256
IP6.ROUTE[3]:                           dst = fe80::/64, nh = ::, mt = 425
```

and in the working state/package I have:
```
build:~ # virsh net-list --all
 Name          State      Autostart   Persistent
--------------------------------------------------
 default       inactive   no          yes
 host-bridge   active     yes         yes
```
via:
```
<network>
 <name>host-bridge</name>
 <forward mode="bridge"/>
 <bridge name="br0"/>
</network>
```
KVM guest instances are started on boot.

All looks to be the same with the non working package version but the guest machines get no connection with their respective NetworkManagers timing out and showing the interface as disconnected.

With the working package I get from dmesg:
```
[    7.191670] r8169 0000:04:00.0 p4p2: link up
[    7.191678] IPv6: ADDRCONF(NETDEV_CHANGE): p4p2: link becomes ready
[    7.205000] br0: port 1(p4p2) entered blocking state
[    7.205002] br0: port 1(p4p2) entered disabled state
[    7.205087] device p4p2 entered promiscuous mode
[    7.205165] br0: port 1(p4p2) entered blocking state
[    7.205166] br0: port 1(p4p2) entered listening state
[   22.236116] br0: port 1(p4p2) entered learning state
[   37.340106] br0: port 1(p4p2) entered forwarding state
[   37.340108] br0: topology change detected, propagating
[   37.361500] NET: Registered protocol family 17
[   38.126142] tun: Universal TUN/TAP device driver, 1.6
[   38.126534] br0: port 2(vnet0) entered blocking state
[   38.126535] br0: port 2(vnet0) entered disabled state
[   38.126567] device vnet0 entered promiscuous mode
[   38.126625] br0: port 2(vnet0) entered blocking state
[   38.126627] br0: port 2(vnet0) entered listening state
[   38.302882] br0: port 3(vnet1) entered blocking state
[   38.302884] br0: port 3(vnet1) entered disabled state
[   38.302923] device vnet1 entered promiscuous mode
[   38.302974] br0: port 3(vnet1) entered blocking state
[   38.302975] br0: port 3(vnet1) entered listening state
[   38.418570] br0: port 4(vnet2) entered blocking state
[   38.418572] br0: port 4(vnet2) entered disabled state
[   38.418607] device vnet2 entered promiscuous mode
[   38.418657] br0: port 4(vnet2) entered blocking state
[   38.418659] br0: port 4(vnet2) entered listening state
[   53.212099] br0: port 2(vnet0) entered learning state
[   53.468099] br0: port 4(vnet2) entered learning state
[   53.468119] br0: port 3(vnet1) entered learning state
[   68.316104] br0: port 2(vnet0) entered forwarding state
[   68.316106] br0: topology change detected, propagating
[   68.576119] br0: port 4(vnet2) entered forwarding state
[   68.576121] br0: topology change detected, propagating
[   68.576143] br0: port 3(vnet1) entered forwarding state
[   68.576144] br0: topology change detected, propagating
```
And with the failing package I get:
```
[    7.357325] r8169 0000:04:00.0 p4p2: link up
[    7.357333] IPv6: ADDRCONF(NETDEV_CHANGE): p4p2: link becomes ready
[    7.369683] br0: port 1(p4p2) entered blocking state
[    7.369685] br0: port 1(p4p2) entered disabled state
[    7.369764] device p4p2 entered promiscuous mode
[    7.369847] br0: port 1(p4p2) entered blocking state
[    7.369848] br0: port 1(p4p2) entered listening state
[   22.492087] br0: port 1(p4p2) entered learning state
[   37.596060] br0: port 1(p4p2) entered forwarding state
[   37.596066] br0: topology change detected, propagating
[   37.616522] NET: Registered protocol family 17
[   38.392030] tun: Universal TUN/TAP device driver, 1.6
[   38.393234] br0: port 2(vnet0) entered blocking state
[   38.393236] br0: port 2(vnet0) entered disabled state
[   38.393272] device vnet0 entered promiscuous mode
[   38.393334] br0: port 2(vnet0) entered blocking state
[   38.393335] br0: port 2(vnet0) entered listening state
[   38.582000] br0: port 3(vnet1) entered blocking state
[   38.582002] br0: port 3(vnet1) entered disabled state
[   38.582039] device vnet1 entered promiscuous mode
[   38.582090] br0: port 3(vnet1) entered blocking state
[   38.582092] br0: port 3(vnet1) entered listening state
[   38.696091] br0: port 4(vnet2) entered blocking state
[   38.696093] br0: port 4(vnet2) entered disabled state
[   38.696131] device vnet2 entered promiscuous mode
[   38.696183] br0: port 4(vnet2) entered blocking state
[   38.696184] br0: port 4(vnet2) entered listening state
[   53.468065] br0: port 2(vnet0) entered learning state
[   53.724065] br0: port 4(vnet2) entered learning state
[   53.724090] br0: port 3(vnet1) entered learning state
[   68.572074] br0: port 2(vnet0) entered forwarding state
[   68.572076] br0: topology change detected, propagating
[   68.828074] br0: port 3(vnet1) entered forwarding state
[   68.828075] br0: topology change detected, propagating
[   68.828094] br0: port 4(vnet2) entered forwarding state
[   68.828095] br0: topology change detected, propagating
```

Is their a missing post install step maybe.

I couldn't find what might be causing this failure in KVM networking with this setup hence my reverting to a prior working snapshot and installing each pending package in turn and rebooting. This was the last package I tried given it's changelog indicating bridge changes.

I do have some additional repositories on this system but they are mainly Python3 / buildbot Kiwi related and do have some outstanding packages held back related to these but again this worked before this package and works again when reverting to pre zypper snapshot of just this package being installed.

Apologies if this report is misplaced, or down to something I have yet to uncover.

**Comment by phillxnet** [comment]
Additionally each KVM guest machine is configured via VMM as:

Specify Shared device name: Bridge name br0
Device model virtio

However I believe they were originally setup to 
"Virtual Network 'host_bridge': Bridge network

which reverts to the above automatically. When the failing for me package was installed I was unable to get any network function via the bridge irrespective of the config within VMM.

Again apologies if this is noise. Reporting in case it help to resolve any issue that might exist. Please ask for any missing info in required. Although this machine is under active production use I will do what I can.

**Comment by phillxnet** [comment]
Linking to what looks like the build.opensuse.org page:
https://build.opensuse.org/package/show/openSUSE:Leap:15.1:Update/suse-module-tools

**Comment by mwilck** [comment]
What is your firewall setup? Are you using firewalld or SuSEfirewall2? Can you work around the issue by stopping the firewall / clearing firewall rules?

The only change that might be responsible for this regression is the line

    softdep bridge post: br_netfilter

in `/etc/modprobe.d/00-system.conf`. Can you please simply comment out that line and see if that fixes your problem?

**Comment by phillxnet** [comment]
@mwilck Thanks for the pointers and feedback.

> What is your firewall setup? Are you using firewalld or SuSEfirewall2?

This install is not upgraded from a prior version and so inherits Leap 15.1’s default of firewalld. 

I have just managed to reproduce this same issue by way of preparing for your suggestions.

After again applying all due updates as of just now (4th Jan 2020) but keeping my prior work-around of
```
zypper addlock suse-module-tools
```
in place all was well.

I rebooted and all was still working. 

I then updated only suse-module-tools by removing the lock:
```
zypper removelock suse-module-tools
```
and then:
```
zypper up
Loading repository data...
Reading installed packages...

The following 2 package updates will NOT be installed:
 python3-cssselect python-rpm-macros

The following package is going to be upgraded:
 suse-module-tools

1 package to upgrade.
Overall download size: 42.4 KiB. Already cached: 0 B. After the operation, 2.8 KiB will be freed.
```
and there after confirmed the new version:
```
zypper info suse-module-tools
Loading repository data...
Reading installed packages...


Information for package suse-module-tools:
------------------------------------------
Repository     : Main Update Repository                                                
Name           : suse-module-tools                                                     
Version        : 15.1.18-lp151.2.4.1                                                   
Arch           : x86_64                                                                
Vendor         : openSUSE                                                              
Installed Size : 79.7 KiB                                                              
Installed      : Yes                                                                   
Status         : up-to-date                                                            
Source package : suse-module-tools-15.1.18-lp151.2.4.1.src 
```
At this point existing and new KVM connections worked.
I then rebooted and thereafter I had no access to the KVM's exactly as per the issue text. I.e. all KVM guests are unable to retrieve their DHCP config from the LAN router.

The firewalld service is running and no changes have been made in all of these procedures:
```
systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: disabled)
   Active: active (running)
     Docs: man:firewalld(1)
 Main PID: 819 (firewalld)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/firewalld.service
           └─819 /usr/bin/python3 -Es /usr/sbin/firewalld --nofork --nopid

Jan 04 15:39:26 build systemd[1]: Starting firewalld - dynamic firewall daemon...
Jan 04 15:39:26 build systemd[1]: Started firewalld - dynamic firewall daemon.
```

> Can you work around the issue by stopping the firewall / clearing firewall rules?

```
systemctl stop firewalld
```
and rebooting one of the KVM's and sure enough it is then able to get it's IP.
```
systemctl disable firewalld
Removed /etc/systemd/system/multi-user.target.wants/firewalld.service.
Removed /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
```
and then rebooting and all KVM guests are again able to retrieve their IP config from real LAN.

Starting firewalld and rebooting a KVM guest and we again have DHCP timeout within the KVM guest:
```
[FAILED] Failed to start Network Manager Wait Online
```
All my KVM guest machines are running Network Manager but span CentOS, Leap15.1, Tumbleweed bases.

Enabled firewalld:
```
systemctl enable firewalld
Created symlink /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service → /usr/lib/systemd/system/firewalld.service.
Created symlink /etc/systemd/system/multi-user.target.wants/firewalld.service → /usr/lib/systemd/system/firewalld.service.
```
rebooted and again across the board failure on all KVM guests network capability with firewalld enabled and the updated suse-module-tools.

> Can you please simply comment out that line and see if that fixes your problem?

Leaving the firewall started and enabled:
```
systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: disabled)
   Active: active (running)
     Docs: man:firewalld(1)
 Main PID: 851 (firewalld)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/firewalld.service
           └─851 /usr/bin/python3 -Es /usr/sbin/firewalld --nofork --nopid

Jan 04 16:10:18 build systemd[1]: Starting firewalld - dynamic firewall daemon...
Jan 04 16:10:18 build systemd[1]: Started firewalld - dynamic firewall daemon.
```
and remarking out the line (101) you suggested in /etc/modprobe.d/00-system.conf
```
...
grep br_netfilter /etc/modprobe.d/00-system.conf 
# Since kernel 3.18 br_netfilter is needed to pass bridged packets to
# netfilter. Load br_netfilter automatically to avoid regressions in SLE12 SP2+
# softdep bridge post: br_netfilter
...
```
before reboot we have this module loaded:
```
lsmod | grep br_netfilter
br_netfilter           24576  0
bridge                184320  2 br_netfilter,ebtable_broute
```
and then rebooting and we then have no br_netfilter loaded, as expected:
```
lsmod | grep br_netfilter
```
and to confirm that firewalld has started on this boot we have:
```
systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: disabled)
   Active: active (running)
     Docs: man:firewalld(1)
 Main PID: 890 (firewalld)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/firewalld.service
           └─890 /usr/bin/python3 -Es /usr/sbin/firewalld --nofork --nopid

Jan 04 16:21:39 build systemd[1]: Starting firewalld - dynamic firewall daemon...
Jan 04 16:21:39 build systemd[1]: Started firewalld - dynamic firewall daemon.
```
And all KVM guests are functioning as expected and able to pickup and use their DHCP network config.

So to me this does look to be the related line within this package update for the issue as reported.

Please let me know what else I can do to help diagnose further this issue. I'm now running this machine with the indicated softdep line remarked out but as I have a reproducing setup here I'm happy to help where I can.

Hope that helps and let me know if you need me to try anything else to further diagnose this issue. This is a production machine so I am somewhat limited but there is always the fantastic boot to snapshot facility.

Could it be that this type of setup (KVM guests bridge access to 'real' LAN), with this indicated as required, br_netfilter module invocation necessitates additional firewall exceptions/rules? I've not seen this indicated elsewhere though. 

Thanks again for tending to this issue and do please let me know if you need me to try anything else to help where I can.

**Comment by mwilck** [comment]
> So to me this does look to be the related line within this package update for the issue as reported.

I suppose if that line is commented out, your host doesn't load the `br_netfilter` module. Please verify by checking `/proc/modules`.

Now `br_netfilter` is responsible for **bridged** packets to be handled by the firewall. Without this module, bridge packets simply pass through the firewall. I guess this is what's happening in your case. Once  `br_netfilter` is loaded, the traffic from the VM's is blocked by the firewall while it's trying to pass the bridge. I suspect your firewall rules. You may have a problem with your rules, which you just didn't notice before because of the missing  `br_netfilter`.

Have you assigned the correct firewalld zone to your bridge devices? In particular, do you let e.g. DHCP traffic pass? Are your firewall rules hand-crafted or set up by libvirt?

**Comment by phillxnet** [comment]
> I suppose if that line is commented out, your host doesn't load the `br_netfilter` module. Please verify by checking `/proc/modules`.

Yes that was what I was trying to prove with the following:

> and then rebooting and we then have no br_netfilter loaded, as expected:
> 
> ```
> lsmod | grep br_netfilter
> ```

And to presumably double check, with that line commented out we get the following from your proc suggestion:
```
cat /proc/modules | grep br_netfilter
```
That command returns nothing, so no br_netfilter presumably confirmed.
I also double check by re-enabling the br_netfilter line and rebooting and sure enough we get:
```
cat /proc/modules | grep br_netfilter
br_netfilter 24576 0 - Live 0xffffffffa0dfe000
bridge 184320 2 ebtable_broute,br_netfilter, Live 0xffffffffa0dd0000
```
Where upon we again have network failure within the KVM guests.

So yes module is definitely not loaded with line removed and is with line in place as per the newer package.

> Without this module, bridge packets simply pass through the firewall. I guess this is what's happening in your case.

Agreed, re:

> Could it be that this type of setup (KVM guests bridge access to 'real' LAN), with this indicated as required, br_netfilter module invocation necessitates additional firewall exceptions/rules? I've not seen this indicated elsewhere though.

And re your comment:

> I suspect your firewall rules. You may have a problem with your rules, which you just didn't notice before because of the missing `br_netfilter`.

Also agreed.

With regard to:

> Have you assigned the correct firewalld zone to your bridge devices? In particular, do you let e.g. DHCP traffic pass? Are your firewall rules hand-crafted or set up by libvirt?

I have done nothing with firewalld with regard to this bridge device and had perhaps wrongly assumed it was functional given the host system is able to use it successfully to access updates etc and to get it's own DHCP from the same network router.

I'll look further into this as my firewalld / bridge knowledge is pretty shaky.

If it turns out that specific firewall rules are now needed then that's great as I then know this and if you could point me to where I can submit docs for openSUSE on setting up this arrangement, which is not infrequently desired, then I can write it up. Assuming I get it working with this module loaded, because as previously stated I've not noticed this as a documented requirement for this setup previously and presumably at least some other distros also have this module in effect. But again I'm often pretty rushed.

Thanks again for your feedback and for helping to narrow down the module/area concerned. I'll look to firewalld config issues and report back here with relevant info.

**Comment by phillxnet** [comment]
@mwilck Quick update.

By stopping firewalld service and running firewalld thus:
```
/usr/bin/python3 -Es /usr/sbin/firewalld --nofork --debug 1
```
I get the following pertinent entries:
```
...
2020-01-05 17:26:46 DEBUG1: config.GetAll('org.fedoraproject.FirewallD1.config')
2020-01-05 17:26:46 DEBUG1: zone.changeZoneOfInterface('', 'p4p2')
2020-01-05 17:26:46 DEBUG1: Setting zone of interface 'p4p2' to 'public'
2020-01-05 17:26:46 DEBUG1: zone.ZoneOfInterfaceChanged('public', 'p4p2')
2020-01-05 17:26:46 DEBUG1: zone.ZoneChanged('public', 'p4p2')
2020-01-05 17:26:46 DEBUG1: zone.changeZoneOfInterface('', 'br0')
2020-01-05 17:26:46 DEBUG1: Setting zone of interface 'br0' to 'public'
2020-01-05 17:26:46 DEBUG1: zone.ZoneOfInterfaceChanged('public', 'br0')
2020-01-05 17:26:46 DEBUG1: zone.ZoneChanged('public', 'br0')
...
```
so firewalld is picking up the bridge and assigning it to the default public zone.

But with a little more reading I've found what looks like the new requirement for setups such as these post suse-module-tools version 15.1.18-lp151.2.4.1 with the now included br_netfilter invocation:

```
firewall-cmd --permanent --direct --passthrough ipv4 -I FORWARD -i br0 -j ACCEPT
```
Which gave the following debug 1 output from firewalld:
```
020-01-05 18:35:11 DEBUG1: config.direct.addPassthrough('ipv4','-I','FORWARD','-i','br0','-j','ACCEPT')
2020-01-05 18:35:11 DEBUG1: config.direct.getSettings()
2020-01-05 18:35:11 DEBUG1: config.direct.update()
2020-01-05 18:35:11 DEBUG1: config.direct.Updated()
2020-01-05 18:35:16 DEBUG1: config.direct.Updated()
```
and:
```
firewall-cmd --permanent --direct --passthrough ipv4 -I FORWARD -o br0 -j ACCEPT
```
with the following in firewalld debug output:
```
2020-01-05 18:36:15 DEBUG1:config.direct.addPassthrough('ipv4','-I','FORWARD','-o','br0','-j','ACCEPT')
2020-01-05 18:36:15 DEBUG1: config.direct.getSettings()
2020-01-05 18:36:15 DEBUG1: config.direct.update()
2020-01-05 18:36:15 DEBUG1: config.direct.Updated()
2020-01-05 18:36:20 DEBUG1: config.direct.Updated()
```

My KVM hosts now look to be happy again network wise. And also work as expected on subsequent reboots.

Given this issue now very much looks like a side effect of the newly introduced default of loading br_netfilter, and we have narrowed down the cause and in my case detailed the newly required forwarding rules which return prior function; do we close this as something like:

Updated module config introduced bridge filtering via br_netfilter?

I'll await your advise.

**Comment by mwilck** [comment]
> ```
> firewall-cmd --permanent --direct --passthrough ipv4 -I FORWARD -o br0 -j ACCEPT
> ```

You shouldn't need to add a direct rule for that. Direct rules should be a last resort if all else fails.
You could try

    firewall-cmd --zone trusted --change-interface br0

Which should have the same affect (the "trusted" zone uses ACCEPT policy) but would be much better maintainable. (For testing this you need to delete the previously created directr rule first).

[The libvirt docs](https://libvirt.org/firewall.html) say that bridges should automatically be added to a zone called "libvirt" which has the required ports already open without allowing everything, which would be better security-wise. But I don't think this is working right in openSUSE at this time, unfortunately. It also depends on firewalld and libvirt versions that haven't reached Leap yet.

**Comment by phillxnet** [comment]
@mwilck Thanks for the firewalld schooling, definitely a shaky area for. I'll try what you suggest soon and report back.

And thanks again for you attention on this issue.

**Comment by mwilck** [comment]
This change is going to be reverted. See https://bugzilla.opensuse.org/show_bug.cgi?id=1158817.

**Comment by phillxnet** [comment]
@mwilck Re:

> This change is going to be reverted. See https://bugzilla.opensuse.org/show_bug.cgi?id=1158817.

Thanks for the head up and the link to the 'slightly' earlier report of this bridge behavioural change in the generic bugzilla. :)

Presumably this issue should now be closed upon the indicated revert; assuming it goes through.
Thanks again for all your work on pursuing this issue, much appreciated.

**Comment by phillxnet** [comment]
@mwilck Given your last comment it looks like this issue should now be closed. It can always be re-opened if required. Just trying to tidy up after myself.

Thanks again for your diligence and communication with regard to this. Most informative and helpful.
